repos:
  - repo: https://github.com/typstyle-rs/pre-commit-typstyle
    rev: v0.14.4
    hooks:
      - id: typstyle

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
