#import "@local/spranzen:0.1.0": *

= Relativitätstheorie
#fragen-counter.update(0)
#frage[Wie lautet das Relativitätsprinzip?]
#missing[]
#frage[Was ist Zeitdilatation?]
#missing[]
#frage[Was ist das Zwillingsparadoxon und wie wird es gelöst?]
#missing[]
#frage[Beschreiben Sie das Michelson-Morley Experiment. Welche Konsequenzen sind daraus zu ziehen?]
#missing[]
#frage[Geben Sie die Lorentztransformation für ein relativ zu S mit der Geschwindigkeit v bewegtes
  System S' an. Erläutern Sie die Konsequenzen]
#missing[]
#frage[Wie ändern sich Längen, Zeiten und die Masse bei hohen Geschwindigkeiten?]
#missing[]
#frage[Welche Größen sind in der Relativitätstheorie invariant gegenüber der Lorentztransformation?]
#missing[]
#frage[Wie lautet der relativistische Energieerhaltungssatz?]
#missing[]
#frage[Zeige das ein bewegte Uhr langsamer geht als eine ruhende]
#missing[]
#frage[Geben Sie eine geometrische Deutung der Lorentzkontraktion und der Zeitdilatation]
#missing[]
#frage[Skizzieren Sie die Herleitung für das Additionstheorem der Geschwindigkeiten]
#missing[]
#frage[Wie lautet das Additionstheorem der Geschwindigkeiten?]
#missing[]
#frage[Stelle die Galileitransformation der Lorentztransformation gegenüber?]
#missing[]
#frage[Was sind die Gründe für die Einführung der Lorentztransformation?]
#missing[]
#frage[Welche Konsequenzen ergeben sich daraus?]
#missing[]
#frage[Was besagt die Energie-Masse-Äquivalentbeziehung]
#missing[]
#frage[Wie lautet der relativistische Energiesatz? Zeigen Sie unter welchen Bedingungen der in der
  klassischen Mechanik gültige Ausdruck für die kinetische Energie folgt.]
#missing[]
#frage[Wie lautet die Formel für die kinetische Energie in der Relativitätstheorie?]
#missing[]
#frage[Wie lautet die Formel für die Gesamtenergie?]
#missing[]
